# Generated by cucumber-sinatra. (2011-06-19 14:59:19 +0200)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', 'testapp')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Website

class WebsiteWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  WebsiteWorld.new
end
